language: java

cache:
  directories:
  - "$HOME/.cache"
  
before_install:
  - chmod +x mvnw
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P s3 -s .travis.settings.xml
script:
  - mvn test -B  -P s3 -s .travis.settings.xml

env:
  global:
    - GITHUB_TOKEN: "5adc2bc01f814f242bb87b09d8a21316f29812ea" #ci
    - SPRING_PROFILES_ACTIVE: cloud

before_deploy:
  - echo 'before_deploy:....'
  - if ! [[ $TRAVIS_TAG ]]; then
      git config --local user.name "jsimao71";
      git config --local user.email "jsimao71@gmail.com";
      export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)};
      git tag $TRAVIS_TAG;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    overwrite: true
    script: "mvn deploy -DskipTests -Ps3 -s .travis.settings.xml"

  
after_deploy: 
  - "echo 'Deployment Done!'"

notifications:
  #email:
  #  - ci@einnovator.org
  slack:
    rooms:
      - "einnovator:yAq0Xm9vZe8oFIRyX53KlphI#ci"
